on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify Generated Code
    steps:
      - name: Run Command
        run: ${{ github.event.inputs.command }}

      - name: Check Diff
        run: |
          DIFF=$(git diff)
          if [[ -n "$DIFF" ]]; then
            echo "The following diff was detected when regenerating code. Run '${{ github.event.inputs.command }}' and commit the changes!"
            git diff
            exit 1
          fi
